[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epac-flatbuffer-formats"
dependencies = [
    "flatbuffers==23.5.26",
    "numpy~=2.0",
    "pydantic~=2.10"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "black",
    "mypy",
    "flake8",
    "Flake8-pyproject",
    "isort",
    "pytest",
    "pytest-benchmark",
    "pdoc",
    "hypothesis",
    "p4p",
    "maturin>=1.14.1",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-autodoc2",
    "myst-parser",
    "sphinx-design",
    "pydata-sphinx-theme"
]

[tool.setuptools_scm]
version_file = "src/epac/flatbuffers/_version.py"

[tool.mypy]
explicit_package_bases = true
mypy_path = ["src"]

[[tool.mypy.overrides]]
module = "flatbuffers.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["epac_flatbuffer_formats_rs"]
ignore_missing_imports = true

[tool.black]
line-length = 88
extend-exclude = "epac_flatbuffer_formats_rs\\.pyi"

[tool.isort]
profile = "black"
line_length = 88
skip_glob = [
    "src/epac/flatbuffers/fbschemas/**",
]

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E501",
]
exclude = [
    ".venv",
    ".git",
    "build",
    "src/epac/flatbuffers/fbschemas",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "rust/epac-flatbuffer-formats-rs/python/tests",
]
