# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class AlarmStatus(object):
    NO_ALARM = 0
    DEVICE = 1
    DRIVER = 2
    RECORD = 3
    DATABASE = 4
    UNDEFINED = 5
