# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional

np = import_numpy()


class AlarmT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AlarmT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAlarmT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def AlarmTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # AlarmT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AlarmT
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0

    # AlarmT
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0

    # AlarmT
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def AlarmTStart(builder: flatbuffers.Builder):
    builder.StartObject(3)


def Start(builder: flatbuffers.Builder):
    AlarmTStart(builder)


def AlarmTAddSeverity(builder: flatbuffers.Builder, severity: int):
    builder.PrependUint16Slot(0, severity, 0)


def AddSeverity(builder: flatbuffers.Builder, severity: int):
    AlarmTAddSeverity(builder, severity)


def AlarmTAddStatus(builder: flatbuffers.Builder, status: int):
    builder.PrependUint16Slot(1, status, 0)


def AddStatus(builder: flatbuffers.Builder, status: int):
    AlarmTAddStatus(builder, status)


def AlarmTAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0
    )


def AddMessage(builder: flatbuffers.Builder, message: int):
    AlarmTAddMessage(builder, message)


def AlarmTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return AlarmTEnd(builder)
