# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class AnyInner(object):
    NONE = 0
    Bool = 1
    Byte = 2
    UByte = 3
    Short = 4
    UShort = 5
    Int = 6
    UInt = 7
    Long = 8
    ULong = 9
    Float = 10
    Double = 11
    String = 12
    BoolArray = 13
    ByteArray = 14
    UByteArray = 15
    ShortArray = 16
    UShortArray = 17
    IntArray = 18
    UIntArray = 19
    LongArray = 20
    ULongArray = 21
    FloatArray = 22
    DoubleArray = 23
    StringArray = 24
