# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any

np = import_numpy()


class ControlT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsControlT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def ControlTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # ControlT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlT
    def LimitLow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # ControlT
    def LimitHigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # ControlT
    def MinStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0


def ControlTStart(builder: flatbuffers.Builder):
    builder.StartObject(3)


def Start(builder: flatbuffers.Builder):
    ControlTStart(builder)


def ControlTAddLimitLow(builder: flatbuffers.Builder, limitLow: float):
    builder.PrependFloat64Slot(0, limitLow, 0.0)


def AddLimitLow(builder: flatbuffers.Builder, limitLow: float):
    ControlTAddLimitLow(builder, limitLow)


def ControlTAddLimitHigh(builder: flatbuffers.Builder, limitHigh: float):
    builder.PrependFloat64Slot(1, limitHigh, 0.0)


def AddLimitHigh(builder: flatbuffers.Builder, limitHigh: float):
    ControlTAddLimitHigh(builder, limitHigh)


def ControlTAddMinStep(builder: flatbuffers.Builder, minStep: float):
    builder.PrependFloat64Slot(2, minStep, 0.0)


def AddMinStep(builder: flatbuffers.Builder, minStep: float):
    ControlTAddMinStep(builder, minStep)


def ControlTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return ControlTEnd(builder)
