# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any

np = import_numpy()


class DimensionT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DimensionT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDimensionT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def DimensionTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # DimensionT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DimensionT
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DimensionT
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DimensionT
    def FullSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DimensionT
    def Binning(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DimensionT
    def Reverse(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(
                self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos)
            )
        return False


def DimensionTStart(builder: flatbuffers.Builder):
    builder.StartObject(5)


def Start(builder: flatbuffers.Builder):
    DimensionTStart(builder)


def DimensionTAddSize(builder: flatbuffers.Builder, size: int):
    builder.PrependInt32Slot(0, size, 0)


def AddSize(builder: flatbuffers.Builder, size: int):
    DimensionTAddSize(builder, size)


def DimensionTAddOffset(builder: flatbuffers.Builder, offset: int):
    builder.PrependInt32Slot(1, offset, 0)


def AddOffset(builder: flatbuffers.Builder, offset: int):
    DimensionTAddOffset(builder, offset)


def DimensionTAddFullSize(builder: flatbuffers.Builder, fullSize: int):
    builder.PrependInt32Slot(2, fullSize, 0)


def AddFullSize(builder: flatbuffers.Builder, fullSize: int):
    DimensionTAddFullSize(builder, fullSize)


def DimensionTAddBinning(builder: flatbuffers.Builder, binning: int):
    builder.PrependInt32Slot(3, binning, 0)


def AddBinning(builder: flatbuffers.Builder, binning: int):
    DimensionTAddBinning(builder, binning)


def DimensionTAddReverse(builder: flatbuffers.Builder, reverse: bool):
    builder.PrependBoolSlot(4, reverse, 0)


def AddReverse(builder: flatbuffers.Builder, reverse: bool):
    DimensionTAddReverse(builder, reverse)


def DimensionTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return DimensionTEnd(builder)
