# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional

np = import_numpy()


class DisplayT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DisplayT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDisplayT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def DisplayTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # DisplayT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DisplayT
    def LimitLow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # DisplayT
    def LimitHigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0

    # DisplayT
    def Description(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DisplayT
    def Units(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DisplayT
    def Precision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DisplayT
    def Form(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint16Flags, o + self._tab.Pos
            )
        return 0


def DisplayTStart(builder: flatbuffers.Builder):
    builder.StartObject(6)


def Start(builder: flatbuffers.Builder):
    DisplayTStart(builder)


def DisplayTAddLimitLow(builder: flatbuffers.Builder, limitLow: float):
    builder.PrependFloat64Slot(0, limitLow, 0.0)


def AddLimitLow(builder: flatbuffers.Builder, limitLow: float):
    DisplayTAddLimitLow(builder, limitLow)


def DisplayTAddLimitHigh(builder: flatbuffers.Builder, limitHigh: float):
    builder.PrependFloat64Slot(1, limitHigh, 0.0)


def AddLimitHigh(builder: flatbuffers.Builder, limitHigh: float):
    DisplayTAddLimitHigh(builder, limitHigh)


def DisplayTAddDescription(builder: flatbuffers.Builder, description: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0
    )


def AddDescription(builder: flatbuffers.Builder, description: int):
    DisplayTAddDescription(builder, description)


def DisplayTAddUnits(builder: flatbuffers.Builder, units: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(units), 0
    )


def AddUnits(builder: flatbuffers.Builder, units: int):
    DisplayTAddUnits(builder, units)


def DisplayTAddPrecision(builder: flatbuffers.Builder, precision: int):
    builder.PrependInt32Slot(4, precision, 0)


def AddPrecision(builder: flatbuffers.Builder, precision: int):
    DisplayTAddPrecision(builder, precision)


def DisplayTAddForm(builder: flatbuffers.Builder, form: int):
    builder.PrependUint16Slot(5, form, 0)


def AddForm(builder: flatbuffers.Builder, form: int):
    DisplayTAddForm(builder, form)


def DisplayTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return DisplayTEnd(builder)
