# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class DisplayForm(object):
    DEFAULT = 0
    STRING = 1
    BINARY = 2
    DECIMAL = 3
    HEX = 4
    EXPONENTIAL = 5
    ENGINEERING = 6
