# automatically generated by the FlatBuffers compiler, do not modify

# namespace:


class DisplayForm(object):
    Default = 0
    String = 1
    Binary = 2
    Decimal = 3
    Hex = 4
    Exponential = 5
    Engineering = 6
