# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any

np = import_numpy()


class EnumT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnumT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnumT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def EnumTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # EnumT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnumT
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EnumT
    def Choices(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # EnumT
    def ChoicesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnumT
    def ChoicesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def EnumTStart(builder: flatbuffers.Builder):
    builder.StartObject(2)


def Start(builder: flatbuffers.Builder):
    EnumTStart(builder)


def EnumTAddIndex(builder: flatbuffers.Builder, index: int):
    builder.PrependInt32Slot(0, index, 0)


def AddIndex(builder: flatbuffers.Builder, index: int):
    EnumTAddIndex(builder, index)


def EnumTAddChoices(builder: flatbuffers.Builder, choices: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(choices), 0
    )


def AddChoices(builder: flatbuffers.Builder, choices: int):
    EnumTAddChoices(builder, choices)


def EnumTStartChoicesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartChoicesVector(builder, numElems: int) -> int:
    return EnumTStartChoicesVector(builder, numElems)


def EnumTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return EnumTEnd(builder)
