# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .AlarmT import AlarmT
from .AnyT import AnyT
from .TimeT import TimeT
from typing import Optional

np = import_numpy()


class NTAttribute(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTAttribute()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTAttribute(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def NTAttributeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # NTAttribute
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTAttribute
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTAttribute
    def Value(self) -> Optional[AnyT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AnyT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTAttribute
    def Tags(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # NTAttribute
    def TagsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTAttribute
    def TagsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # NTAttribute
    def Descriptor(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTAttribute
    def Alarm(self) -> Optional[AlarmT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AlarmT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTAttribute
    def Time(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTAttribute
    def SourceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NTAttribute
    def Source(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def NTAttributeStart(builder: flatbuffers.Builder):
    builder.StartObject(8)


def Start(builder: flatbuffers.Builder):
    NTAttributeStart(builder)


def NTAttributeAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0
    )


def AddName(builder: flatbuffers.Builder, name: int):
    NTAttributeAddName(builder, name)


def NTAttributeAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0
    )


def AddValue(builder: flatbuffers.Builder, value: int):
    NTAttributeAddValue(builder, value)


def NTAttributeAddTags(builder: flatbuffers.Builder, tags: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(tags), 0
    )


def AddTags(builder: flatbuffers.Builder, tags: int):
    NTAttributeAddTags(builder, tags)


def NTAttributeStartTagsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartTagsVector(builder, numElems: int) -> int:
    return NTAttributeStartTagsVector(builder, numElems)


def NTAttributeAddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(descriptor), 0
    )


def AddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    NTAttributeAddDescriptor(builder, descriptor)


def NTAttributeAddAlarm(builder: flatbuffers.Builder, alarm: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(alarm), 0
    )


def AddAlarm(builder: flatbuffers.Builder, alarm: int):
    NTAttributeAddAlarm(builder, alarm)


def NTAttributeAddTime(builder: flatbuffers.Builder, time: int):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(time), 0
    )


def AddTime(builder: flatbuffers.Builder, time: int):
    NTAttributeAddTime(builder, time)


def NTAttributeAddSourceType(builder: flatbuffers.Builder, sourceType: int):
    builder.PrependInt32Slot(6, sourceType, 0)


def AddSourceType(builder: flatbuffers.Builder, sourceType: int):
    NTAttributeAddSourceType(builder, sourceType)


def NTAttributeAddSource(builder: flatbuffers.Builder, source: int):
    builder.PrependUOffsetTRelativeSlot(
        7, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0
    )


def AddSource(builder: flatbuffers.Builder, source: int):
    NTAttributeAddSource(builder, source)


def NTAttributeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return NTAttributeEnd(builder)
