# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .AlarmT import AlarmT
from .AnyT import AnyT
from .CodecT import CodecT
from .DimensionT import DimensionT
from .DisplayT import DisplayT
from .NTAttribute import NTAttribute
from .TimeT import TimeT
from typing import Optional

np = import_numpy()


class NTNDArray(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTNDArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTNDArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def NTNDArrayBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # NTNDArray
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTNDArray
    def Value(self) -> Optional[AnyT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AnyT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def Codec(self) -> Optional[CodecT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = CodecT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def CompressedSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # NTNDArray
    def UncompressedSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # NTNDArray
    def Dimension(self, j: int) -> Optional[DimensionT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DimensionT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def DimensionLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTNDArray
    def DimensionIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # NTNDArray
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # NTNDArray
    def DataTimeStamp(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def Attribute(self, j: int) -> Optional[NTAttribute]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = NTAttribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def AttributeLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTNDArray
    def AttributeIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # NTNDArray
    def Descriptor(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTNDArray
    def Alarm(self) -> Optional[AlarmT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AlarmT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def TimeStamp(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTNDArray
    def Display(self) -> Optional[DisplayT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DisplayT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def NTNDArrayStart(builder: flatbuffers.Builder):
    builder.StartObject(12)


def Start(builder: flatbuffers.Builder):
    NTNDArrayStart(builder)


def NTNDArrayAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0
    )


def AddValue(builder: flatbuffers.Builder, value: int):
    NTNDArrayAddValue(builder, value)


def NTNDArrayAddCodec(builder: flatbuffers.Builder, codec: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(codec), 0
    )


def AddCodec(builder: flatbuffers.Builder, codec: int):
    NTNDArrayAddCodec(builder, codec)


def NTNDArrayAddCompressedSize(builder: flatbuffers.Builder, compressedSize: int):
    builder.PrependInt64Slot(2, compressedSize, 0)


def AddCompressedSize(builder: flatbuffers.Builder, compressedSize: int):
    NTNDArrayAddCompressedSize(builder, compressedSize)


def NTNDArrayAddUncompressedSize(builder: flatbuffers.Builder, uncompressedSize: int):
    builder.PrependInt64Slot(3, uncompressedSize, 0)


def AddUncompressedSize(builder: flatbuffers.Builder, uncompressedSize: int):
    NTNDArrayAddUncompressedSize(builder, uncompressedSize)


def NTNDArrayAddDimension(builder: flatbuffers.Builder, dimension: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(dimension), 0
    )


def AddDimension(builder: flatbuffers.Builder, dimension: int):
    NTNDArrayAddDimension(builder, dimension)


def NTNDArrayStartDimensionVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartDimensionVector(builder, numElems: int) -> int:
    return NTNDArrayStartDimensionVector(builder, numElems)


def NTNDArrayAddUniqueId(builder: flatbuffers.Builder, uniqueId: int):
    builder.PrependInt32Slot(5, uniqueId, 0)


def AddUniqueId(builder: flatbuffers.Builder, uniqueId: int):
    NTNDArrayAddUniqueId(builder, uniqueId)


def NTNDArrayAddDataTimeStamp(builder: flatbuffers.Builder, dataTimeStamp: int):
    builder.PrependUOffsetTRelativeSlot(
        6, flatbuffers.number_types.UOffsetTFlags.py_type(dataTimeStamp), 0
    )


def AddDataTimeStamp(builder: flatbuffers.Builder, dataTimeStamp: int):
    NTNDArrayAddDataTimeStamp(builder, dataTimeStamp)


def NTNDArrayAddAttribute(builder: flatbuffers.Builder, attribute: int):
    builder.PrependUOffsetTRelativeSlot(
        7, flatbuffers.number_types.UOffsetTFlags.py_type(attribute), 0
    )


def AddAttribute(builder: flatbuffers.Builder, attribute: int):
    NTNDArrayAddAttribute(builder, attribute)


def NTNDArrayStartAttributeVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartAttributeVector(builder, numElems: int) -> int:
    return NTNDArrayStartAttributeVector(builder, numElems)


def NTNDArrayAddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    builder.PrependUOffsetTRelativeSlot(
        8, flatbuffers.number_types.UOffsetTFlags.py_type(descriptor), 0
    )


def AddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    NTNDArrayAddDescriptor(builder, descriptor)


def NTNDArrayAddAlarm(builder: flatbuffers.Builder, alarm: int):
    builder.PrependUOffsetTRelativeSlot(
        9, flatbuffers.number_types.UOffsetTFlags.py_type(alarm), 0
    )


def AddAlarm(builder: flatbuffers.Builder, alarm: int):
    NTNDArrayAddAlarm(builder, alarm)


def NTNDArrayAddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    builder.PrependUOffsetTRelativeSlot(
        10, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0
    )


def AddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    NTNDArrayAddTimeStamp(builder, timeStamp)


def NTNDArrayAddDisplay(builder: flatbuffers.Builder, display: int):
    builder.PrependUOffsetTRelativeSlot(
        11, flatbuffers.number_types.UOffsetTFlags.py_type(display), 0
    )


def AddDisplay(builder: flatbuffers.Builder, display: int):
    NTNDArrayAddDisplay(builder, display)


def NTNDArrayEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return NTNDArrayEnd(builder)
