# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .AlarmT import AlarmT
from .AnyT import AnyT
from .ControlT import ControlT
from .DisplayT import DisplayT
from .TimeT import TimeT
from typing import Optional

np = import_numpy()


class NTScalarAny(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarAny()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarAny(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def NTScalarAnyBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # NTScalarAny
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarAny
    def Value(self) -> Optional[AnyT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AnyT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAny
    def Descriptor(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTScalarAny
    def Alarm(self) -> Optional[AlarmT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AlarmT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAny
    def TimeStamp(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAny
    def Display(self) -> Optional[DisplayT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DisplayT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAny
    def Control(self) -> Optional[ControlT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ControlT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def NTScalarAnyStart(builder: flatbuffers.Builder):
    builder.StartObject(6)


def Start(builder: flatbuffers.Builder):
    NTScalarAnyStart(builder)


def NTScalarAnyAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0
    )


def AddValue(builder: flatbuffers.Builder, value: int):
    NTScalarAnyAddValue(builder, value)


def NTScalarAnyAddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(descriptor), 0
    )


def AddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    NTScalarAnyAddDescriptor(builder, descriptor)


def NTScalarAnyAddAlarm(builder: flatbuffers.Builder, alarm: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(alarm), 0
    )


def AddAlarm(builder: flatbuffers.Builder, alarm: int):
    NTScalarAnyAddAlarm(builder, alarm)


def NTScalarAnyAddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0
    )


def AddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    NTScalarAnyAddTimeStamp(builder, timeStamp)


def NTScalarAnyAddDisplay(builder: flatbuffers.Builder, display: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(display), 0
    )


def AddDisplay(builder: flatbuffers.Builder, display: int):
    NTScalarAnyAddDisplay(builder, display)


def NTScalarAnyAddControl(builder: flatbuffers.Builder, control: int):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(control), 0
    )


def AddControl(builder: flatbuffers.Builder, control: int):
    NTScalarAnyAddControl(builder, control)


def NTScalarAnyEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return NTScalarAnyEnd(builder)
