# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .AlarmT import AlarmT
from .AnyOuter import AnyOuter
from .ControlT import ControlT
from .DisplayT import DisplayT
from .TimeT import TimeT
from typing import Optional

np = import_numpy()


class NTScalarAll(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarAll()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTScalarAll(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def NTScalarAllBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # NTScalarAll
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarAll
    def Value(self) -> Optional[AnyOuter]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AnyOuter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAll
    def Descriptor(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTScalarAll
    def Alarm(self) -> Optional[AlarmT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AlarmT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAll
    def TimeStamp(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAll
    def Display(self) -> Optional[DisplayT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DisplayT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTScalarAll
    def Control(self) -> Optional[ControlT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ControlT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def NTScalarAllStart(builder: flatbuffers.Builder):
    builder.StartObject(6)


def Start(builder: flatbuffers.Builder):
    NTScalarAllStart(builder)


def NTScalarAllAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0
    )


def AddValue(builder: flatbuffers.Builder, value: int):
    NTScalarAllAddValue(builder, value)


def NTScalarAllAddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(descriptor), 0
    )


def AddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    NTScalarAllAddDescriptor(builder, descriptor)


def NTScalarAllAddAlarm(builder: flatbuffers.Builder, alarm: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(alarm), 0
    )


def AddAlarm(builder: flatbuffers.Builder, alarm: int):
    NTScalarAllAddAlarm(builder, alarm)


def NTScalarAllAddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0
    )


def AddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    NTScalarAllAddTimeStamp(builder, timeStamp)


def NTScalarAllAddDisplay(builder: flatbuffers.Builder, display: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(display), 0
    )


def AddDisplay(builder: flatbuffers.Builder, display: int):
    NTScalarAllAddDisplay(builder, display)


def NTScalarAllAddControl(builder: flatbuffers.Builder, control: int):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(control), 0
    )


def AddControl(builder: flatbuffers.Builder, control: int):
    NTScalarAllAddControl(builder, control)


def NTScalarAllEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return NTScalarAllEnd(builder)
