# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .AlarmT import AlarmT
from .Column import Column
from .DisplayT import DisplayT
from .TimeT import TimeT
from typing import Optional

np = import_numpy()


class NTTable(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNTTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def NTTableBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # NTTable
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTTable
    def Labels(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # NTTable
    def LabelsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTTable
    def LabelsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # NTTable
    def Value(self, j: int) -> Optional[Column]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Column()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTTable
    def ValueLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NTTable
    def ValueIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # NTTable
    def Descriptor(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NTTable
    def Alarm(self) -> Optional[AlarmT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = AlarmT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTTable
    def TimeStamp(self) -> Optional[TimeT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = TimeT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NTTable
    def Display(self) -> Optional[DisplayT]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DisplayT()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def NTTableStart(builder: flatbuffers.Builder):
    builder.StartObject(6)


def Start(builder: flatbuffers.Builder):
    NTTableStart(builder)


def NTTableAddLabels(builder: flatbuffers.Builder, labels: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(labels), 0
    )


def AddLabels(builder: flatbuffers.Builder, labels: int):
    NTTableAddLabels(builder, labels)


def NTTableStartLabelsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartLabelsVector(builder, numElems: int) -> int:
    return NTTableStartLabelsVector(builder, numElems)


def NTTableAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0
    )


def AddValue(builder: flatbuffers.Builder, value: int):
    NTTableAddValue(builder, value)


def NTTableStartValueVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)


def StartValueVector(builder, numElems: int) -> int:
    return NTTableStartValueVector(builder, numElems)


def NTTableAddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(descriptor), 0
    )


def AddDescriptor(builder: flatbuffers.Builder, descriptor: int):
    NTTableAddDescriptor(builder, descriptor)


def NTTableAddAlarm(builder: flatbuffers.Builder, alarm: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(alarm), 0
    )


def AddAlarm(builder: flatbuffers.Builder, alarm: int):
    NTTableAddAlarm(builder, alarm)


def NTTableAddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    builder.PrependUOffsetTRelativeSlot(
        4, flatbuffers.number_types.UOffsetTFlags.py_type(timeStamp), 0
    )


def AddTimeStamp(builder: flatbuffers.Builder, timeStamp: int):
    NTTableAddTimeStamp(builder, timeStamp)


def NTTableAddDisplay(builder: flatbuffers.Builder, display: int):
    builder.PrependUOffsetTRelativeSlot(
        5, flatbuffers.number_types.UOffsetTFlags.py_type(display), 0
    )


def AddDisplay(builder: flatbuffers.Builder, display: int):
    NTTableAddDisplay(builder, display)


def NTTableEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return NTTableEnd(builder)
