# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any

np = import_numpy()


class PulseID(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PulseID()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPulseID(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def PulseIDBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # PulseID
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PulseID
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Uint64Flags, o + self._tab.Pos
            )
        return 0

    # PulseID
    def TimeStamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(
                flatbuffers.number_types.Float64Flags, o + self._tab.Pos
            )
        return 0.0


def PulseIDStart(builder: flatbuffers.Builder):
    builder.StartObject(2)


def Start(builder: flatbuffers.Builder):
    PulseIDStart(builder)


def PulseIDAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUint64Slot(0, value, 0)


def AddValue(builder: flatbuffers.Builder, value: int):
    PulseIDAddValue(builder, value)


def PulseIDAddTimeStamp(builder: flatbuffers.Builder, timeStamp: float):
    builder.PrependFloat64Slot(1, timeStamp, 0.0)


def AddTimeStamp(builder: flatbuffers.Builder, timeStamp: float):
    PulseIDAddTimeStamp(builder, timeStamp)


def PulseIDEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return PulseIDEnd(builder)
