# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .PulseID import PulseID
from flatbuffers.table import Table
from typing import Optional

np = import_numpy()


class PVData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PVData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPVData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def PVDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # PVData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PVData
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PVData
    def Data(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # PVData
    def SourceName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PVData
    def PulseId(self) -> Optional[PulseID]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PulseID()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def PVDataStart(builder: flatbuffers.Builder):
    builder.StartObject(4)


def Start(builder: flatbuffers.Builder):
    PVDataStart(builder)


def PVDataAddDataType(builder: flatbuffers.Builder, dataType: int):
    builder.PrependUint8Slot(0, dataType, 0)


def AddDataType(builder: flatbuffers.Builder, dataType: int):
    PVDataAddDataType(builder, dataType)


def PVDataAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def AddData(builder: flatbuffers.Builder, data: int):
    PVDataAddData(builder, data)


def PVDataAddSourceName(builder: flatbuffers.Builder, sourceName: int):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0
    )


def AddSourceName(builder: flatbuffers.Builder, sourceName: int):
    PVDataAddSourceName(builder, sourceName)


def PVDataAddPulseId(builder: flatbuffers.Builder, pulseId: int):
    builder.PrependUOffsetTRelativeSlot(
        3, flatbuffers.number_types.UOffsetTFlags.py_type(pulseId), 0
    )


def AddPulseId(builder: flatbuffers.Builder, pulseId: int):
    PVDataAddPulseId(builder, pulseId)


def PVDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return PVDataEnd(builder)
