# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any

np = import_numpy()


class TimeT(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TimeT()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTimeT(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def TimeTBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # TimeT
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TimeT
    def SecondsPastEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TimeT
    def Nanoseconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TimeT
    def UserTag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0


def TimeTStart(builder: flatbuffers.Builder):
    builder.StartObject(3)


def Start(builder: flatbuffers.Builder):
    TimeTStart(builder)


def TimeTAddSecondsPastEpoch(builder: flatbuffers.Builder, secondsPastEpoch: int):
    builder.PrependInt64Slot(0, secondsPastEpoch, 0)


def AddSecondsPastEpoch(builder: flatbuffers.Builder, secondsPastEpoch: int):
    TimeTAddSecondsPastEpoch(builder, secondsPastEpoch)


def TimeTAddNanoseconds(builder: flatbuffers.Builder, nanoseconds: int):
    builder.PrependInt32Slot(1, nanoseconds, 0)


def AddNanoseconds(builder: flatbuffers.Builder, nanoseconds: int):
    TimeTAddNanoseconds(builder, nanoseconds)


def TimeTAddUserTag(builder: flatbuffers.Builder, userTag: int):
    builder.PrependInt32Slot(2, userTag, 0)


def AddUserTag(builder: flatbuffers.Builder, userTag: int):
    TimeTAddUserTag(builder, userTag)


def TimeTEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return TimeTEnd(builder)
