# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .NTScalarAny import NTScalarAny
from typing import Optional

np = import_numpy()


class Waveform(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Waveform()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWaveform(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def WaveformBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # Waveform
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Waveform
    def DataX(self) -> Optional[NTScalarAny]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = NTScalarAny()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Waveform
    def DataY(self) -> Optional[NTScalarAny]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = NTScalarAny()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def WaveformStart(builder: flatbuffers.Builder):
    builder.StartObject(2)


def Start(builder: flatbuffers.Builder):
    WaveformStart(builder)


def WaveformAddDataX(builder: flatbuffers.Builder, dataX: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(dataX), 0
    )


def AddDataX(builder: flatbuffers.Builder, dataX: int):
    WaveformAddDataX(builder, dataX)


def WaveformAddDataY(builder: flatbuffers.Builder, dataY: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(dataY), 0
    )


def AddDataY(builder: flatbuffers.Builder, dataY: int):
    WaveformAddDataY(builder, dataY)


def WaveformEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return WaveformEnd(builder)
