# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from .NTScalarAny import NTScalarAny
from typing import Optional

np = import_numpy()


class XYData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = XYData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsXYData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def XYDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x70\x76\x61\x30", size_prefixed=size_prefixed
        )

    # XYData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # XYData
    def X(self) -> Optional[NTScalarAny]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = NTScalarAny()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # XYData
    def Y(self) -> Optional[NTScalarAny]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = NTScalarAny()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def XYDataStart(builder: flatbuffers.Builder):
    builder.StartObject(2)


def Start(builder: flatbuffers.Builder):
    XYDataStart(builder)


def XYDataAddX(builder: flatbuffers.Builder, x: int):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(x), 0
    )


def AddX(builder: flatbuffers.Builder, x: int):
    XYDataAddX(builder, x)


def XYDataAddY(builder: flatbuffers.Builder, y: int):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(y), 0
    )


def AddY(builder: flatbuffers.Builder, y: int):
    XYDataAddY(builder, y)


def XYDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()


def End(builder: flatbuffers.Builder) -> int:
    return XYDataEnd(builder)
