name: Code CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test-cloud:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up development environment
        run: ./dev.py setup venv
      - name: Run pre-commit hooks
        run: ./dev.py pre-commit
      - name: Run tests
        run: ./dev.py test
  test-selfhosted:
    if: false
    runs-on: [self-hosted, python3.10]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up development environment
        run: ./dev.py setup venv
      - name: Run pre-commit hooks
        run: ./dev.py pre-commit
      - name: Run tests
        run: ./dev.py test
